### ISSUE TITLE
unable to delete by id

### ISSUE THREAD

**Issue by ralyodio** [surrealdb/surrealdb.js#72] opened 2023-02-07 09:51 UTC
I have a schema as follows:

```
#!/bin/bash

# See: https://gist.githubusercontent.com/koakh/fbbc37cde630bedcf57acfd4d6a6956b/raw/ec0d25ce0dba9b729f4e8d379149e4b99cced7bc/gistfile1.txt

. .env
. .env.local

DATA="DEFINE TABLE user SCHEMAFULL
  PERMISSIONS 
    FOR select FULL,
    FOR update WHERE id = \$auth.id, 
    FOR create, delete NONE;
DEFINE FIELD email ON user TYPE string;
DEFINE FIELD phone ON user TYPE string;
DEFINE FIELD username ON user TYPE string;
DEFINE FIELD createdAt ON user TYPE datetime;
DEFINE FIELD updatedAt ON user TYPE datetime;
DEFINE FIELD loggedInAt ON user TYPE datetime;
DEFINE FIELD password ON user TYPE string PERMISSIONS NONE;
DEFINE FIELD settings ON user TYPE object;
DEFINE FIELD settings.location ON user TYPE geometry (point);
DEFINE FIELD settings.timezone ON user TYPE string;
DEFINE FIELD settings.languages ON user TYPE array;
DEFINE FIELD settings.languages.* ON user TYPE string;
DEFINE FIELD settings.offset ON user TYPE string;
DEFINE FIELD verify ON user TYPE object;
DEFINE FIELD verify.email ON user TYPE object;
DEFINE FIELD verify.email.code ON user TYPE string;
DEFINE FIELD verify.email.expiration ON user TYPE datetime;
DEFINE FIELD verify.email.status ON user TYPE string;
DEFINE FIELD verify.phone ON user TYPE object;
DEFINE FIELD verify.phone.code ON user TYPE string;
DEFINE FIELD verify.phone.expiration ON user TYPE datetime;
DEFINE FIELD verify.phone.status ON user TYPE string;
DEFINE INDEX idx_email ON user COLUMNS email UNIQUE;
DEFINE INDEX idx_username ON user COLUMNS username UNIQUE;
"

curl -k -L -s --compressed POST \
	--header "Accept: application/json" \
	--header "NS: ${DB_NS}" \
	--header "DB: ${DB_DB}" \
	--user "root:root" \
	--data "${DATA}" \
	${DB_SQL_URL}


DATA="DEFINE SCOPE allusers
  -- the JWT session will be valid for 14 days
  SESSION 14d
  -- The optional SIGNUP clause will be run when calling the signup method for this scope
  -- It is designed to create or add a new record to the database.
  -- If set, it needs to return a record or a record id
  -- The variables can be passed in to the signin method
  SIGNUP ( CREATE user SET username = \$username, email = \$email, phone = \$phone, password = crypto::argon2::generate(\$password), createdAt = \$createdAt, updatedAt = \$updatedAt )
  -- The optional SIGNIN clause will be run when calling the signin method for this scope
  -- It is designed to check if a record exists in the database.
  -- If set, it needs to return a record or a record id
  -- The variables can be passed in to the signin method
  SIGNIN ( SELECT * FROM user WHERE email = \$email AND crypto::argon2::compare(password, \$password) )
  -- this optional clause will be run when calling the signup method for this scope
"

curl -k -L -s --compressed POST \
	--header "Accept: application/json" \
	--header "NS: ${DB_NS}" \
	--header "DB: ${DB_DB}" \
	--user "root:root" \
	--data "${DATA}" \
	${DB_SQL_URL}

```

and `gigs` as follows:

```
#!/bin/bash

. .env
. .env.local

DATA="DEFINE TABLE gigs SCHEMALESS
  PERMISSIONS 
    FOR select FULL,
    FOR create WHERE \$scope = \"allusers\",
	FOR update WHERE createdBy = \$auth.id,
	FOR delete WHERE createdBy = \$auth.id;
"
# 	-- FOR select WHERE \$scope = \"allusers\" -- limit to only users in db

curl -k -L -s --compressed POST \
	--header "Accept: application/json" \
	--header "NS: ${DB_NS}" \
	--header "DB: ${DB_DB}" \
	--user "root:root" \
	--data "${DATA}" \
	${DB_SQL_URL}

```

The problem is `db.delete(id)` doesn't work and neither does `db.query(`DELETE ${id}`)`.

No errors or warnings. Just doesn't get deleted. It happens on all my projects. I believe this was fixed in this repo but there has never been a new release and its been about 3-4 months now.

Can you release `surrealdb.js` more frequently for us who would like to continue to use surrealdb?

I cannot recommend using this database framework if you cannot delete.

**Comment by chenasraf** [comment] 2023-03-22 22:57
Also affected by this issue, can this be prioritized please? It's kind of ridiculous we can't delete records

**Comment by ralyodio** [comment] 2023-03-24 04:26
yes, i've even talked to Tobias about it. He asked me to try nightly but I couldn't export my data from stable release because they don't escape quotes. :P

I'm glad its not just me, so far it seems to be just you and I.

**Comment by kearfy** [comment] 2023-04-10 10:42
Hey! On a first look, I'd say this is caused by this bit:
```sql
    FOR create, delete NONE;
```
Which will result in scope users not being able to delete records. 
Could you try to remove as a root/namespace/database user? Please tell me if I'm missing something here

**Comment by kearfy** [comment] 2023-04-10 10:44
Maybe you could try with this table definition?
```sql
DEFINE TABLE user SCHEMAFULL
  PERMISSIONS 
    FOR select FULL,
    FOR update, delete WHERE id = $auth.id, 
    FOR create NONE;
```

**Comment by ralyodio** [comment] 2023-04-10 10:58
That's just for users though. I can't delete a comment which is this:

```
DATA="DEFINE TABLE comments SCHEMALESS
  PERMISSIONS 
    FOR select FULL,
    FOR create WHERE \$scope = \"allusers\",
	FOR update WHERE createdBy = \$auth.id,
	FOR delete WHERE createdBy = \$auth.id;
"
```

**Comment by kearfy** [comment] 2023-04-11 17:33
@ralyodio I will close this issue in favor of https://github.com/surrealdb/surrealdb/issues/1739, as it's not related to surrealdb.js itself

**Closed by kearfy** 2023-04-11 17:33 UTC

**Comment by ralyodio** [comment] 2023-04-13 10:25
Your suggestion doesn't work
