### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by icebob** [surrealdb/surrealdb.js#4] opened 2022-09-04 15:25 UTC
Hi,

I would like to the the SurrealDB and I'm following the steps on the site but it doesn't work and I don't find information what's wrong.

I've started the server with `docker run --name surrealdb -d -p 8000:8000 surrealdb/surrealdb:latest start` as it's mentioned in the [install](https://surrealdb.com/install) page.
I've copied the Node.js example code from [here](https://surrealdb.com/docs/integration/libraries/nodejs) but when I start it gives error:
```
ERROR r [AuthenticationError]: There was a problem with authentication
    at c.Ye (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:69967)
    at c.<anonymous> (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:66686)
    at c.r (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52384)
    at D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52586
    at Array.forEach (<anonymous>)
    at c.value (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52563)
    at s.<anonymous> (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:65324)
    at D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52586
    at Array.forEach (<anonymous>)
    at s.value (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52563)
```

I think the problem is that, the container started without user/pass, but the example code use `root` for them, but if I skip them, in `db.signin` I've got the same problem. If I skip the whole `signin` I've got 
```
ERROR Error: There was a problem with the database: The table does not exist
```

**Comment by koakh** [comment] 2022-09-04 21:35
Hello @icebob 

I confirm that with docker run command it fails

after some time, I found that the problem is the TAG latest that don't is the latest and greatest version

to work one must use implicit TAB version 1.0.0-beta.7

ex working version

```shell
docker run --name surrealdb -p 8000:8000 surrealdb/surrealdb:1.0.0-beta.7 start -b 0.0.0.0:8000 --log trace memory
```

you can run it with surrealdb from binary to

```shell
# in memory / default
./surreal start --log trace --user root --pass root
# or with rocksdb
surreal start --user root --pass root file:mydb
```

or with docker compose with

```yml
services:
  db:
    image: surrealdb/surrealdb:1.0.0-beta.7
    command: "start -b 0.0.0.0:8000 -u root -p root memory"
    ports:
      - 8000:8000
```

thanks and sorry for the delay

**Comment by tobiemh** [comment] 2022-09-04 21:41
Hi @koakh and @icebob!

The `latest` tag on SurrealDB is the `1.0.0-beta.7` version I'm pretty sure. Can you make sure you ensure that you update the docker container to the latest version and try it again?

```bash
docker pull surrealdb/surrealdb:latest
```

Then you can check which version it is using...

```bash
docker run --name surrealdb surrealdb/surrealdb:latest version
```

With the latest version (currently `1.0.0-beta.7`), this issue should be fixed @icebob 👍 😀

**Comment by icebob** [comment] 2022-09-05 17:48
I've started with @koakh's command:
![image](https://user-images.githubusercontent.com/306521/188497012-eca2a85b-c0b9-4f81-84e2-031e6032d4f1.png)

But the issue is the same:
```
ERROR r [AuthenticationError]: There was a problem with authentication
    at c.Ye (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:69967)
    at c.<anonymous> (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:66686)
    at c.r (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52384)
    at D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52586
    at Array.forEach (<anonymous>)
    at c.value (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52563)
    at s.<anonymous> (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:65324)
    at D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52586
    at Array.forEach (<anonymous>)
    at s.value (D:\Work\tmp\surrealdb-demo\node_modules\surrealdb.js\dist\lib\index.cjs:1:52563)
```

**Comment by koakh** [comment] 2022-09-05 18:25
H @icebob 

can you delete all surrealdb images and containers and launch this commands, and send the outcome

ex

```shell
# force remove container
$ docker container ls -a  | grep surrealdb
4fe816028733   surrealdb/surrealdb:latest   "/surreal start"         20 hours ago   Up 20 hours                                                                                                     surrealdb

# remove container
$ docker rm surrealdb -f
surrealdb

$ docker image ls | grep surrealdb
surrealdb/surrealdb                          1.0.0-beta.7                   8b3724bf2423   6 days ago      50.3MB
surrealdb/surrealdb                          latest                         8b3724bf2423   6 days ago      50.3MB

$ docker image rm 8b3724bf2423 -f
Untagged: surrealdb/surrealdb:1.0.0-beta.7
Untagged: surrealdb/surrealdb:latest
Untagged: surrealdb/surrealdb@sha256:591b255ab7fa0db174fd419f1d8bb162592da46a1169c5055f657a92a7633032
Deleted: sha256:8b3724bf2423fb186217a4145365d0acd0e0088d8277a4f637da82f7bfefaf17

$ docker run --name surrealdb surrealdb/surrealdb:latest version
Unable to find image 'surrealdb/surrealdb:latest' locally
latest: Pulling from surrealdb/surrealdb
0a602d5f6ca3: Already exists 
d7fbeaa2da3f: Already exists 
a1f1879bb7de: Already exists 
88882f3c82b2: Already exists 
Digest: sha256:591b255ab7fa0db174fd419f1d8bb162592da46a1169c5055f657a92a7633032
Status: Downloaded newer image for surrealdb/surrealdb:latest
surreal 1.0.0-beta.7 for linux on x86_64

# launch
$ docker run --name surrealdb -d -p 8000:8000 surrealdb/surrealdb:latest start --user root --pass root
```

what I figure out is that we need `--user root --pass root` flags, else it won't work, I try a bunch of times, allways replicate the same error without the flags

i even try with standalone binary, and if we don't pass the flags it won't work, I can be wrong, like in my repply above, I think @tobiemh is the right person to tell what's happens, but for now try running with `--user root --pass root` until @tobiemh answear

thanks @icebob

**Comment by icebob** [comment] 2022-09-05 19:42
@koakh you are right, with `--user root --pass root` works fine. Thanks!

By the way, if it's intentional just need to update the docker run commands in the docs.

**Comment by koakh** [comment] 2022-09-05 19:47
Glad to know you are ready @icebob 
@tobiemh is the best person to finish this issue, and improve the docs, etc

**Comment by CypElf** [comment] 2022-09-10 18:58
I'm facing the exact same issue, except it still doesn't work, even with the `--user` and `--pass` flags set correctly (using the standalone executable version 1.0.0-beta.7 on Windows).

**Comment by Lightnet** [comment] 2022-09-18 23:34
It took some time to find some docs from the users. It hard to find but docs pages and some area plain sighed. Here some links. https://surrealdb.com/features#permissions this deal with signup and login. https://gist.github.com/koakh/fbbc37cde630bedcf57acfd4d6a6956b Here some more information. Credit to the surreal discord with search feature help a lot.

**Comment by VixieTSQ** [comment] 2022-09-19 02:53
Best to rename this issue to something like "Authentication errors"?

**Comment by MrEmanuel** [comment] 2022-09-25 14:14
I had the same problem. 

I solved it by removing all docker images and adding user and password to the docker run command. 
```
docker run --name surrealdb -d -p 8000:8000 surrealdb/surrealdb:latest start --user root --pass root
```

The official dockerfile should be updated to fix this issue imo.

**Comment by mathe42** [comment] 2022-10-04 10:12
@MrEmanuel You didn't need to remove all docker images the --user, --pass arguments had to be added...

@tobiemh Think it is fine to close this

**Comment by KeyOnTech** [comment] 2023-03-23 21:30
Leaving this here for anyone that lands on this page at 3am in the future....

Trying to setup SurrealDB and Docker-Compose... 
Its in the docs heres the link...
https://tutorials.surrealdb.com/community/host-with-docker-compose.html

Those that don't want to read here's a sample docker-compose file for you too
Good night from future you ....

`
# # save this file and run the command below...  in terminal...
# docker-compose up -d --build

# # the user name and password are below change to whatever you want...
# # --user change_me_user_name 
# # --pass change_me_password
# #     command: start --user username1 --pass password1 file:/data/database.db
# # change me below 

version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    command: start --user username1 --pass password1 file:/data/database.db
    ports:
     - 8000:8000
    volumes:
      - ./data:/data

`

**Comment by kearfy** [comment] 2023-04-06 07:35
Heya, I'm going to close this issue as it's related to documentation for the side (read: https://github.com/surrealdb/www.surrealdb.com) and as the documentation has been greatly expanded this week. Thanks!

**Closed by kearfy** 2023-04-06 07:35 UTC
