### ISSUE TITLE
Question: How can I use multiple sessions at the same time

### ISSUE THREAD

**Issue by LrsChrSch** [surrealdb/surrealdb.js#87] opened 2023-04-21 16:45 UTC
I'm using Oak (Deno) to create a simple API with user authentication and I've stumbled across a certain scenario:

1. User1 makes a request. This triggers a middleware to authenticate that user with the db. Part of the request is an action that takes some time (for example upload some files or wait for a timeout). After that action the database should update the user record (or perform any query that needs User1's authentication)
2. Log in User2 within the time it takes for the action from (2) to complete. This changes the authenticated state of the db object to User2
3. User1's action completes, but the query fails because it now tries to perform the query of User1 using the Authentication of User2

I'm sure that I'm missing some fundamental part of how this should work. The main question is: How can I use a different session for each request so that every surreal session uses their own authentication and can't be mixed up?

I could of course create new surreal objects that instantiate their own connections every time ofc. But that seems really counter intuitive and most importantly: very slow.

Hope you can help!

**Comment by LrsChrSch** [comment] 2023-04-21 18:46
Alright, short update.

I managed to fix this by opening a new connection to SurrealDB on every request and attaching the db object to ctx.state. Which isn't great of course (would be nicer to just use 1 with different auth states as proposed here: https://github.com/surrealdb/surrealdb.js/issues/61).

The reason why I mentioned that this would be slow is because... it was. I used `const db = new Surreal("http://localhost:8000/rpc");` to create the connection. Turns out that this is several seconds slower than using `const db = new Surreal("http://127.0.0.1:8000/rpc");` for some reason.

With the faster speed, invoking a new connection everytime is fine for my use case. I'll leave this open for now in case anyone has a better solution. But feel free to close this if you feel that this isn't relevant anymore :)

**Comment by kearfy** [comment] 2023-05-04 17:41
Closing this as a duplicate of #61 

Anyways, to help you out: This is not possible over WebSockets as of now. The client drivers for each language are merely a representation of the APIs out there, and the WS API in SurrealDB currently does not support this :)

**Comment by kearfy** [comment] 2023-05-04 17:42
In #95 I'm adding an HTTP client, you could have multiple http clients with different credentials

**Closed by kearfy** 2023-05-04 17:41 UTC
