### ISSUE TITLE
`TypeError: import_ws.WebSocket is not a constructor` using Vite

### ISSUE THREAD

**Issue by coutouly** [surrealdb/surrealdb.js#158] opened 2023-07-27 13:58 UTC
### Describe the bug

try to connect with websocket inside a quasar/vite application

### Steps to reproduce

```
/ src/boot/surreal.ts


import Surreal, { Database } from 'surrealdb.js';

import { boot } from 'quasar/wrappers';

const db: Database = new Surreal();
await db.connect('http://' + window.location.host + ':8000/rpc',  {
	ns: 'test',
	db: 'test',
    auth: {
		user: 'root',
		pass: 'root',
	}
    }
  );


export default boot(async({ app }) => {
  app.config.globalProperties.$db = db;
});

export { db};
```
i get this error:
```
client-entry.js?t=1690465885626:146 [Quasar] boot error: TypeError: import_ws.WebSocket is not a constructor
    at SurrealSocket.open (SurrealSocket.ts:63:13)
    at WebSocketStrategy.connect (websocket.ts:78:15)
    at surreal.ts:9:10
```

the error is from:
surrealsocket.ts   
`
63   this.unprocessedLiveResponses = {};`

### Expected behaviour

connect.

### SurrealDB version

docker nightly

### SurrealDB.js version

beta 9

### Contact Details

lucile.coutouly@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment] 2023-07-30 19:15
Hi @coutouly, this looks like a bundling issue on your side to me, but I will try to replicate this issue soon!
PS; A friendly note that a `Database` is not defined nor exported exported from the package anywhere 😃

**Comment by thyaravind** [comment] 2023-08-22 05:41
@kearfy , I am receiving the same error when running `surrealdb.js` in a sveltekit project. Copying the details below.

```typescript
import Surreal from "surrealdb.js";

const db = new Surreal(import.meta.env.VITE_SURREAL_URL, {})
``` 


The error log:
<img width="654" alt="CleanShot 2023-08-22 at 11 11 21@2x" src="https://github.com/surrealdb/surrealdb.js/assets/52457571/40182550-c471-41d4-b2d2-dae0bd2fe08b">

Kindly let me know if I am missing something. Thanks

**Comment by kearfy** [comment] 2023-08-22 07:37
Hiya, could you set up a github repository with a reproducable example for me by any chance? It would greatly help me to figure out where this is going wrong, as I've never worked with Sveltekit before :)
Schedule is a bit busy, so I can't make a promise timewise, but I will look into this shortly!

**Comment by rharasim** [comment] 2023-08-30 16:21
Same error here with Nest.js:

```
Import:
import { Surreal } from 'surrealdb.js'; 

Problematic part:
new Surreal('http://127.0.0.1:8000')

Error message:
TypeError: node_js_1.default is not a constructor
```

**Comment by nhphero** [comment] 2023-09-29 09:16
Temporary solution
import Surreal from "https://cdn.jsdelivr.net/npm/surrealdb.js";

**Comment by rharasim** [comment] 2023-10-18 08:59
This problem appears with typescript version >=4.9.3

**Comment by kearfy** [comment] 2023-10-30 08:45
Hey everyone, I'm still having issues to reproduce this issue, I would like to fix it for you all however! Would it be possible for anyone in this conversation that can reproduce it to setup a small repo with a reproducable example? Thanks!

**Comment by macjuul** [comment] 2023-10-30 14:26
I ran into this issue myself when working on a web project using vite, however updating vite to the latest version (4.5.0) fixed it for me.

**Comment by thyaravind** [comment] 2023-11-01 14:51
@kearfy, It is working fine for me now. I gave another attempt to test the SDK and it is working like a breeze. 

The last time I reported the issue, I was using the latest version of the npm package (Aug 22, 2023). Right now, I am using `"surrealdb.js": "^0.11.0"`

Not sure if something has changed on the package itself. I was using same vite and svelte version back then as what it is now.

``` 
    "@sveltejs/kit": "^1.5.0",
    "svelte": "^3.54.0",
    "tslib": "^2.4.1",
    "typescript": "^4.9.3",
    "vite": "^4.0.0"
```

**Comment by kearfy** [comment] 2023-11-01 15:05
Very interesting! It could be patched in another library that vite/svelte is using. As for surrealdb.js, I noticed that unws was patched, so that could have changed too.

Anyways, glad that it works for you now!

**Comment by suleimanas** [comment] 2023-11-20 18:00
Same here with Quasar, it's a problem with vite @quasar/app-vite,
you can make it work if you go to `\node_modules\@quasar\app-vite>` and upgrade vite. i did `npm i vite@latest` <-- just to test it or as a temporary solution

**Comment by kearfy** [comment] 2023-11-28 12:39
Will close this as it seems upgrading dependencies fixes this issue!

**Closed by kearfy** 2023-11-28 12:39 UTC
Labels: bug
