### ISSUE TITLE
Bug: import_ws.WebSocket is not a constructor

### ISSUE THREAD

**Issue by lalokob** [surrealdb/surrealdb.js#197] opened 2023-11-18 22:29 UTC
### Describe the bug

Hello, I am fascinated with this new technology. I am exploring its benefits and functionalities, but when trying to implement it in a quasar/vue project, by instantiating the "new Surreal" class and using the connect('host') method; an exception pops up: "import_ws.WebSocket is not a constructor"

### Steps to reproduce

I imported the surrealdb module:
import Surreal from 'surrealdb.js';

I copy and paste the example from the documentation (I change my credentials)
![Captura de pantalla 2023-11-18 162621](https://github.com/surrealdb/surrealdb.js/assets/46539730/0b9ccf15-8ce5-4b0a-b0ac-7499adf0f7c7)

### Expected behaviour

Be able to establish a connection to the database (running in docker). Also, with postman it works excellent!!

### SurrealDB version

1.0.0

### SurrealDB.js version

0.11.0

### Contact Details

lalo.kob@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment] 2023-11-28 12:41
Heya! This seems like it's a duplicate of #158. Please make sure all dependencies surrounding Vite are up-to-date!

**Closed by kearfy** 2023-11-28 12:41 UTC
Labels: bug
